### ISSUE TITLE
Comment box disappearing after slightly moving.

### ISSUE THREAD

**Issue by kasrasadeghi** [iampueroo/rComments#1]
It's extraordinarily difficult to get the box to stay put. You move your mouse a little bit and it goes away. Even if you're hovering over the comment link, and you move your mouse down to click "next comment" it'll vanish. The only way I've managed to click on the "next comment" button in the bubble is by scrolling.

**Comment by iampueroo** [comment]
@kasrasadeghi 

Oh wow, just saw that you submitted an issue! Sorry for the late reply.

Currently the logic is to NOT hide the box if the mouse leaves the comment link from the bottom. It works pretty well for me, but there are times when it fails. I'm guessing there's a small window after it leaves and when it is NOT over the box. Quick few questions:

1) Are you using a mouse? (I develop using a touchpad)
2) Any way you could make a gif of it happening? (No worries if not)

I'll get right on making a fix and pushing it out!

Thanks for submitting an issue, again apologies for the late reply, I totally didn't see the issues.

**Comment by iampueroo** [comment]
@kasrasadeghi 
Improved the hovering logic, look for the update in the coming day!
