### ISSUE TITLE
I ported it to Firefox in like 3 minutes :)

### ISSUE THREAD

**Issue by andreicristianpetcu** [iampueroo/rComments#2]
Hi,

I ported your extension [to Firefox](https://my.owndrive.com/index.php/s/SLImJZzcCzM63G4/download) using [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified). I did not upload it to addons.mozilla.org since I am not the author. Please make an official port!

More info about Firefox support for Chrome extensions [here](https://arewee10syet.com/) and [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs).

Thank you!

**Comment by azizLIGHT** [comment]
Just tried this and it only loads 1 top comment and gives an error for other top level and child comments:  "Error: Reddit did not respond."  Also there are no upvote/downvote buttons.
![image](https://user-images.githubusercontent.com/8013867/33563472-132847b6-d8e6-11e7-9f6f-639db92b3860.png)

I'm on FF 56 and wondering if it still works for you on FF?
