### ISSUE TITLE
Using laptop touchpad, tapping on "Next Comment" closes popup

### ISSUE THREAD

**Issue by azizLIGHT** [iampueroo/rComments#4]
I use a laptop and noticed this problem. After hovering over the comments link and opening the comments popup, if I use the touchpad and actually press and click down on "Next Comment", the new top level comment is loaded underneath immediately, as expected. However, if I use the touchpad and tap (to indicate a click) on "Next Comment", the popup actually closes! Then if I move the mouse back over the comments link, I can see that there are now 2 top level comments shown  in the popup. So, the request to load the next comment was received and acted upon successfully, but it seems like its not correctly detecting whether or not if I should still be seeing the comments popup or not, since the mouse has moved away from the comments link and is on top of the "Next comment" popup link (which when it disappears, leaves the mouse on top of the next reddit post title)

I'm not sure if this is specific to my laptop or touchpad. I'm on an ASUS X205TA on windows 8.1. I will try to test on other machines and report back

**Comment by iampueroo** [comment]
Hey! Thanks for submitting the issue!

I kept trying to recreate this on my own machine (macbook pro) and cannot. I'll try the following: 

1) I'll have access to a few windows machines this weekend, and will try to recreate it then
2) I'll take a look at how what events I'm using, maybe I can figure out what is happening without recreating it myself.

What might help, though, is if you are able to take a video or gif of it! Just to see it. No worries if not, again I'll be trying to recreate it this weekend.

**Comment by azizLIGHT** [comment]
Thanks for looking into this
Here's a gif of when I use [actual clicks on my touchpad](https://thumbs.gfycat.com/UnkemptIdleArthropods.webp)
And here's where the problem occurs: [when I tap on my touchpad, the popup disappears every time](https://thumbs.gfycat.com/ExcellentDisastrousChameleon.webp)

**Comment by azizLIGHT** [comment]
I think this was some laptop software specific problem. I never experienced this on other machines. I will close this.
