### ISSUE TITLE
Upvote / Downvote Functionality removed for old.reddit.com unnecessarily

### ISSUE THREAD

**Issue by iampueroo** [iampueroo/rComments#8]
The voting functionality was removed as I thought it wasn't working in either the old or new reddit. 

It definitely cannot come back simply in new reddit (no CSS classes to steal from as they're obfuscated).

For old.reddit.com, I only saw request issues (CORS and/or non 200s) when making the vote API requests. From [this issue](https://github.com/iampueroo/rComments/pull/5#issuecomment-634017090), it seems like it was working earlier. If the request can work on `old.reddit.com`, then voting functionality can be supported again.

**Comment by azizLIGHT** [comment]
I forgot to mention. Voting works fine on old.reddit.com when logged in, but ALSO voting works fine on www.reddit.com if your reddit user preferences are set to enable old reddit (opt out of redesign). I've had that setting enabled for a long time like many others and just browse www.reddit.com while still using old reddit.

The preference to enable old reddit is here:
via new reddit: https://www.reddit.com/settings -> Account -> flip switch on for "Opt out of the redesign"
via old reddit: https://www.reddit.com/prefs/ -> beta options on bottom of page -> uncheck "Use new Reddit as my default experience"

Hope that helps

**Comment by iampueroo** [comment]
Now working on `old.reddit.com` and `reddit.com` with the old styles

**Comment by UmbraVivens** [comment]
i am on old.reddit.com and opted out of the redesign but the vote buttons aren't showing up for me

**Comment by iampueroo** [comment]
@UmbraVivens I suspect that the reason is that your browser hasn't updated the extension yet. The version with the fix is `1.2.1`. I just tested the version on chrome and it has the voting functionality. 

If you'd like, you can manually update on chrome by going to `chrome://extensions/` -> toggling `Developer Mode` on the top right and then clicking `Update`. Let me know if you're on the right version but still not seeing the arrows.

Moving forward, I'll make sure to close issues only after the the extension has been published and I'll include the version number with it.

**Comment by UmbraVivens** [comment]
ok, after sleeping and turning on my pc again, the vote buttons are back (forgot to mention i uninstalled and reinstalled the extension as a "hard" way of updating before making the comment above)

**Comment by iampueroo** [comment]
👍 good to hear, and sorry again about the inconvenience.

**Comment by azizLIGHT** [comment]
> Now working on `old.reddit.com` and `reddit.com` with the old styles

Confirmed working for me for both domains on 1.2.1 with old reddit preference enabled
