### ISSUE TITLE
Dark mode comments are not dark when not logged in

### ISSUE THREAD

**Issue by azizLIGHT** [iampueroo/rComments#9]
On new reddit (redesign), using the website's built-in dark mode, comments popups are in light mode:
![image](https://user-images.githubusercontent.com/8013867/84571992-24dd3380-ad65-11ea-8281-fa51a7b2780b.png)

Not using RES (RES night mode option doesn't work in new reddit anyway)

**Comment by iampueroo** [comment]
Ah, I assume this occurs when nightmode is on but you are **not** logged in? Currently we check with the logged in user's [metadata](https://github.com/iampueroo/rComments/blob/master/source/rComments.js#L473) to check for nightmode. I didn't realize it was available not being logged in.

**Comment by azizLIGHT** [comment]
Basically yes, not logged in, forgot to mention that. I opened reddit in incognito and flipped the night mode on and looked at a comment popup. It initially loads as dark for 1 second while its getting content, then it turns white like in the screenshot and remains white for more comment loads

**Comment by azizLIGHT** [comment]
It seems like the color alternates between dark/light when you mouse over again. So if it renders in light mode once, mouse over again and it'll be dark mode this time. For me that's a workaround for now

**Comment by iampueroo** [comment]
The fix should be out on `v1.2.3`. The popup box should match light/dark mode in a persistent way **but only after a reload**. I didn't find it necessary to have to do a constant check on every popup whether or not the page changed toggle dark mode. To summarize this should be the behavior:
1) Toggle dark mode **on** (when previously it was off)
2) Without refreshing, comment box is still on light mode, sad
3) Refresh
4) Comment box is on dark mode and dark mode will persist across page reloads. Yay!
5) Toggle dark mode **off**
6) Without refreshing, comment box is still on dark mode, sad
7) Refresh
8) Comment box is on light mode and light mode will persist across page reloads. Yay!
etc etc

**Comment by iampueroo** [comment]
So i'm not sure what happened there^ but I think this was fixed with this commit: https://github.com/iampueroo/rComments/commit/32ce926a33344070d5bdaa6301cb996a1e65d3e4. 

I just tested it toggling dark mode on and off when logged out on both Chrome and Firefox and it works as expected (but after one page load). Resolving this, but please reopen if you're seeing something different!
